### ISSUE TITLE
Gauss-Jacobi branching bug

### ISSUE THREAD

**Issue by pkofod** [JuliaApproximation/FastGaussQuadrature.jl#57] opened 2017-11-15 11:29 UTC
I havn't looked through the code base too closely but I just spent the morning trying to fix a bug in DistQuads.jl. I couldn't find out what on earth was wrong with my code. I thought it was my normalization after doing the change of variables, but then I found out it was the weights coming from `gaussjacobi`.

Look at the figures below. `x` is alpha and `y` is beta in the Beta distribution. North-west shows the difference between the mean of the beta distribution from Distributions and the one from DistQuads, north-east shows the mean from Distributions, south-west shows the mean from DistQuads (based on gauss-quadrature), south-east is just `gamma(alpha)*gamma(beta)/gamma(alpha*beta)` for debugging purposes. You see that it NaNs out a some point. I could change to `big` here but that doesn't matter for this purpose.

First, I am calling `gaussjacobi`
![jacobinowork](https://user-images.githubusercontent.com/8431156/32833558-88d6b470-c9ff-11e7-9114-4db5cdce2099.png)

then, I am calling JacobiRec for the recursive version and I am getting
![jacworks](https://user-images.githubusercontent.com/8431156/32833399-111d4084-c9ff-11e7-841d-a0a957520ebf.png)

Basically, calling `JacobiRec` gives me the correct answer - but something happens around `(x,y).>6` and the weights are complete rubbish if you use  `gaussjacobi`. I'll just switch to JacobiRec in my code, but figured you would want to know.

![jacosmall](https://user-images.githubusercontent.com/8431156/32833897-c52e9c7a-ca00-11e7-9f63-db65193f99c3.png)

This is the code
```julia
using Distributions, DistQuads, Plots
plotlyjs()
xs = linspace(0.0001,150.0,300)
ys = linspace(0.0001,150.0,300)
z1 = [mean(Beta(x, y))-mean(DistQuad(Beta(x, y))) for x = xs, y = ys]
z2 = [mean(Beta(x, y)) for x = xs, y = ys]
z3 = [mean(DistQuad(Beta(x, y))) for x = xs, y = ys]
z4 = [gamma(x)*gamma(y)/gamma(x+y) for x = xs, y = ys]

p1 = heatmap(xs,ys,z1)
p2 = heatmap(xs,ys,z2)
p3 = heatmap(xs,ys,z3)
p4 = heatmap(xs,ys,z4)
plot(p1,p2,p3,p4)
```
called on two different versions of DistQuads (one calling gaussjacobi and one calling JacobiRec).

**Comment by hyrodium** [comment] 2021-02-20 05:34
Does this bug still exist? Some bugs around `gaussjacobi` is already solved such as #46.
I couldn't reproduce the bug, and I think this bug may be already solved.

**Comment by pkofod** [comment] 2021-02-20 16:11
I don't know, I don't use the package any more :)

**Comment by hyrodium** [comment] 2021-02-21 03:10
Ah, I found the bug, and the bug was already solved!

## FastGaussQuadrature `v0.3.3` (on Julia `v0.6.4`)
```julia
julia> x1,w1 = gaussjacobi(100,prevfloat(-0.5),prevfloat(5.))
jacobirec([-0.996358, -0.992797, -0.988347, -0.982984, -0.976708, -0.969523, -0.961433, -0.952445, -0.942569, -0.931812  …  0.958087, 0.966399, 0.973807, 0.980305, 0.985886, 0.990544, 0.994276, 0.997078, 0.998948, 0.999883], [1.42529e-15, 5.491e-14, 7.47679e-13, 5.89509e-12, 3.28204e-11, 1.43132e-10, 5.20315e-10, 1.64188e-9, 4.62542e-9, 1.18718e-8  …  1.23189, 1.26093, 1.28728, 1.31076, 1.3312, 1.34847, 1.36243, 1.37299, 1.38008, 1.38363])

julia> x0,w0 = gaussjacobi(100,-0.5,5)
([-0.996358, -0.992797, -0.988347, -0.982984, -0.976708, -0.969523, -0.961433, -0.952445, -0.942569, -0.931812  …  0.958087, 0.966399, 0.973807, 0.980305, 0.985886, 0.990544, 0.994276, 0.997078, 0.998948, 0.999883], [1.42529e-15, 5.491e-14, 7.47679e-13, 5.89509e-12, 3.28204e-11, 1.43132e-10, 5.20315e-10, 1.64188e-9, 4.62542e-9, 1.18718e-8  …  1.23189, 1.26093, 1.28728, 1.31076, 1.3312, 1.34847, 1.36243, 1.37299, 1.38008, 1.38363])

julia> norm(w0-w1)
2.534417104592726e-13
```

## FastGaussQuadrature `v0.3.0` (on Julia `v0.6.4`)
```julia
julia> x1,w1 = gaussjacobi(100,prevfloat(-0.5),prevfloat(5.))
([-0.996358, -0.992797, -0.988347, -0.982984, -0.976708, -0.969523, -0.961433, -0.952445, -0.942569, -0.931812  …  0.958087, 0.966399, 0.973807, 0.980305, 0.985886, 0.990544, 0.994276, 0.997078, 0.998948, 0.999883], [1.42529e-15, 5.491e-14, 7.47679e-13, 5.89509e-12, 3.28204e-11, 1.43132e-10, 5.20315e-10, 1.64188e-9, 4.62542e-9, 1.18718e-8  …  1.23189, 1.26093, 1.28728, 1.31076, 1.3312, 1.34847, 1.36243, 1.37299, 1.38008, 1.38363])

julia> x0,w0 = gaussjacobi(100,-0.5,5)
([-0.996358, -0.992797, -0.988347, -0.982984, -0.976708, -0.969523, -0.961433, -0.952445, -0.942569, -0.931812  …  0.958087, 0.966399, 0.973807, 0.980305, 0.985886, 0.990544, 0.994276, 0.997078, 0.998948, 0.999883], [4.26285e-17, 1.64229e-15, 2.23622e-14, 1.76315e-13, 9.81617e-13, 4.28091e-12, 1.5562e-11, 4.91065e-11, 1.38341e-10, 3.5507e-10  …  0.0368444, 0.0377129, 0.038501, 0.0392032, 0.0398146, 0.040331, 0.0407486, 0.0410645, 0.0412764, 0.0413827])

julia> norm(w0-w1)
5.580856138868244
```

**Comment by hyrodium** [comment] 2021-02-21 03:11
Thanks for the bug report, I'll close this issue.

**Closed by hyrodium** 2021-02-21 03:11 UTC
